# Generated by Django 4.0.6 on 2022-07-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogMe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logreg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
