# Generated by Django 4.0.6 on 2022-07-23 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LogReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
                ('confirm_password', models.CharField(max_length=32, verbose_name='Confirm Password')),
                ('profile_name', models.CharField(max_length=32, verbose_name='Profile Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('snack', 'Snack'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='Breakfast', max_length=60, verbose_name='Type of Meal')),
                ('meal_name', models.CharField(max_length=255, verbose_name='Meal Name')),
                ('mealId', models.CharField(max_length=255, verbose_name='Meal ID')),
                ('quantity', models.IntegerField(db_column='item_quantity', default=1, verbose_name='Number of servings')),
                ('date', models.DateField()),
                ('calories', models.IntegerField(default=0, verbose_name='Calories')),
                ('meal_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='LogMe_app.logreg')),
            ],
        ),
    ]
